name: Build TicketManager

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Make Gradle wrapper executable
      run: chmod +x ./gradlew

    - name: Build project
      run: ./gradlew build

    - name: Upload plugin jars
      uses: actions/upload-artifact@v4
      with:
        name: ticketmanager-artifacts
        path: |
          TicketManager*/build/libs/*.jar
          **/build/libs/*.jar
