name: Build TicketManager

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build TicketManager Standalone
      run: cd Standalone && gradle build

    - name: Upload Standalone Plugin Jar
      uses: actions/upload-artifact@v4
      with:
        name: ticketmanager-standalone
        path: Standalone/build/libs/*.jar
