##############################################
##############################################
#       TicketManager Config File
#             Version 7.0.0
##############################################
##############################################
#
# Plugin Proudly Made by: HoshiKurama
#
# All permissions and commands can
# be found on the GitHub wiki page.
# https://github.com/HoshiKurama/TicketManager
#
# ##########################################
#       Locale:
# ##########################################
#
# Force Locale: Forces specific language to be used for commands and responses.
# Values: true, false
Force_Locale: false
#
# Preferred Locale: Locale to use when player locale is not found. Using a non-supported
# locale will cause TicketManager to internally default to Canadian English.
# Values:
#   'en_CA' = Canadian English
#   'en_US' = US English
#   'en_UK' = UK English
#   'de_DE' = German
Preferred_Locale: 'en_CA'
#
# Console Locale: Locale Console will use. Using a non-supported locale will cause
# TicketManager to internally default to Preferred_Locale. When discord support is
# enabled, discord locale uses this value.
# Values: Same as in Preferred_Locale
Console_Locale: 'en_CA'
#
# ##########################################
#                 Cooldown:
# ##########################################
#
# Use Cool-down: Determine if cool-downs should be applied to ticket commands
# that create or modify a ticket. Cool-downs apply to ALL users without the
# override permission.
# Values: true, false
Use_Cooldowns: false
#
# Ticket Modification Cool-down: Time in seconds before a user is able to create or
# modify a ticket. This applies to ALL users without the override permission if
# cool-downs are enabled.
Cooldown_Time: 0
#
# ##########################################
#           Database Settings:
# ##########################################
#
# Database mode: Type of database used. Internally defaults
# to Cached_SQLite if invalid value is used. Information only needs
# to be filled out for the desired database type.
#
#                 SQLite:
# Stores information in the SQLite file in the TicketManager folder.
# Pros: + No setup.
#       + No external database needed.
#       + Faster than MySQL for search and history command.
# Cons: - Stores data in TicketManager folder.
#       - Easier to overwhelm than Memory or MySQL.
#
#                 MySQL:
# Stores information in a database that may or may not be on the server.
# Pros: + Can handle more traffic than SQLite.
#       + Can be separate from server storage.
# Cons: - Must have MySQL database.
#       - Search and history commands slower.
#
#                 Memory:
# Memory refers to TicketManager's custom solution for running the entire
# database in RAM. Data is backed up throughout normal server operations or
# on server shutdowns. It is then loaded back into RAM on startup.
# Pros: + Incredibly responsive
#       + Incredibly fast queries
# Cons: - Any power loss or server crash will result in all data beyond
#         the last backup being lost.
#
#                Cached SQL:
# Blend between the Memory and SQLite option. Data is loaded from SQLite into
# the Memory model, and all changes reflect in the SQLite file.
# Pros: + Extreme speed of the Memory mode
#       + Reliability of the SQLite mode
# Cons: - Possibly slower database initialization
#
# Values: 'MYSQL','SQLITE','MEMORY', 'CACHED_SQLITE'
Database_Mode: 'CACHED_SQLITE'
#
# ######################
#    MySQL Database
# ######################
MySQL_Port: ''
MySQL_Host: ''
MySQL_DBName: ''
MySQL_Username: ''
MySQL_Password: ''
#
# ######################
#   Memory as Database
# ######################
# Time in seconds between database backups being made
Memory_Backup_Frequency: 600
#
# ###########################################
#              Error Printing
# ###########################################
#
# The following setting determine how TicketManager displays unexpected error.
# These values do not affect error in-game. Please use permission nodes for that
# instead. These values only affect the way error messages appear in Console.
#
# Print Modified Stacktrace: Prints a modified stacktrace only containing where
# errors occurred in TicketManager's code. Useful for quickly deciding where the issue
# lies, but not always enough to determine where the issue lies.
# Values: true, false
Print_Modified_Stacktrace: true
#
# Print Full Stacktrace: Prints a full stacktrace containing all much more info
# than the modified stacktrace. Contains more information, but harder to sort through.
# Values: true, false
Print_Full_Stacktrace: false
#
# ###########################################
#             Discord Settings
# ###########################################
#
# Discord Bot: On ticket updates of your choosing, TicketManager
# is able to send a notification to a text channel in your Discord server.
# This is NOT plug and play. You will be required to generate the
# bot token yourself and tell the bot where to send these messages.
# Instructions are provided on the TicketManager wiki on GitHub.
# Values: true, false
Use_Discord_Bot: false
#
# Bot Token: Token generated by user for the Discord bot.
Discord_Bot_Token: ''
#
# Channel ID: Text Channel ID for the text channel the bot should
# send messages to. MUST be inputted as a numeric value.
Discord_Channel_ID: -1
#
# ######################
#     Discord Flags
# ######################
# The following flags are used to determine when TicketManager
# will send a notification to Discord (if enabled). Does not
# fire for silent commands.
# Values: true, false
Discord_Notify_On_Assign: true
Discord_Notify_On_Close: true
Discord_Notify_On_Close_All: true
Discord_Notify_On_Comment: true
Discord_Notify_On_Create: true
Discord_Notify_On_Reopen: true
Discord_Notify_On_Priority_Change: true
#
# ###########################################
#                   Other
# ###########################################
#
# Colour Code:
# Provides simple colour customization for the theme of the
# plugin. The following formats are supported:
#     - Literals for default colours ('red' or 'white')
#     - Integers (1551768)
#     - Hex codes. (#17AD98)
#     - Legacy colour codes with '&' (&3)
# Refer to Kyori MiniMessage for more information!
Colour_Code: '&3'
#
# Allow Unread Ticket Updates: When users other than the creator
# make ticket changes, the creator can optionally be alerted at
# regular intervals or on login which tickets have a status change.
# This is NOT the same alert one immediately receives on ticket
# status change. Setting value to 'false' prevents TicketManager
# from flagging a ticket as unread.
# Values: true, false
Allow_Unread_Ticket_Updates: true
#
# Allow Update Checking: Server can check that the latest version of
# TicketManager is installed during startup or reloads.
# Values: true, false
Allow_UpdateChecking: true
#
# Enable Advanced Visual Control: By default, TicketManager uses its own
# formatting for visual information. However, users can instruct TicketManager to
# create external locale files and use these instead. This allows end users to customize
# virtually all visual components of the plugin. Missing files will be regenerated when
# this mode is enabled. Missing components will simply default to the internal version.
# To understand the formatting, please refer to Kyori MiniMessage documentation.
#
# NOTE: Please do NOT use this to add new languages. Adding new languages is not possible
# for end users, and it is much more beneficial to offer translations for all other
# users by submitting your work!
# Values: true, false
Enable_Advanced_Visual_Control: false